server:
  port: 8086
  servlet:
    context-path: '/thumbelina'

spring:
  data:
    mongodb:
      uri: "mongodb://admin:abc123def456@localhost:27017/admin"
      database: 'sich_intent'

logging:
  file: 'thumbelina.log'

wechat:
  mini-program:
    app-id: "wxc09ec1faa22cb365"
    app-secret: "6916806cbe159c5714e8530201b1fa74"
  pay:
    mch-id: "1494681852"
    api-key: "5A226E214F184906BA081D416C4BBEDU"
    cert-path: "classpath:apiclient_cert.p12"
    notify-url: "https://api.jolii.net/thumbelina/wechat/pay/notify"
    refund-notify-url: "https://api.jolii.net/thumbelina/wechat/pay/notify/refund"
    refund-retry-times: 2
    # Unit => Millisecond
    refund-retry-delay: 50

assesscode:
  amount-to-fee: 0, 1, 2, 3
