server:
  port: 9000

spring:
  data:
    mongodb:
      uri: "mongodb://thumbelina:B409F51C-98CC-4FED-A8AD-E7516A4BF42D@localhost:27017/sich_intent"

logging:
  path: '/home/thumbelina/'

wechat:
  pay:
    cert-path: "/home/thumbelina/apiclient_cert.p12"

assesscode:
  amount-to-fee: 0, 1, 2, 3
