server:
  port: 8086
  servlet:
    context-path: '/thumbelina'

spring:
  data:
    mongodb:
      uri: "mongodb://admin:abc123def456@localhost:27017/admin"
      database: 'sich_intent'

logging:
  file: 'thumbelina.log'
